---
abstract: 'Authorize with Box.com '
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OAuth2-Box
requires:
  Carp::Assert: 0.20
  HTTP::Tiny: 0.034
  JSON: 2.53
  Moo: 1.003001
  Test::Exception: 0.32
  Test::More: 0.98
  Type::Tiny: 0.026
  URI: 1.59
resources:
  bugtracker: http://github.com/reneeb/OAuth2-Box/issues
  homepage: http://github.com/reneeb/OAuth2-Box
  repository: git://github.com/reneeb/OAuth2-Box.git
version: 0.03
